# config.py

ALTURA = 700
LARGURA = 500
TAMANHO_TILE = 48
PLAYER_ALVO_Y = ALTURA * 2 // 3 - 100

VEL_SCROLL_INICIAL = 0.25
VEL_SCROLL_MAX = 3.0
SCORE_PARA_MAX_VEL = 80

SAFE_ZONE_LINHAS = 1

ARVORE_PREGEN_LINHAS = 10
ARVORE_APARECIMENTO_MS = 500
ARVORE_MARGEM_MANUTENCAO = (ARVORE_PREGEN_LINHAS + 4) * TAMANHO_TILE
ARVORE_CHANCE_BASE = 0.025
ARVORE_CHANCE_EXTRA_MAX = 0.025
ARVORE_CHANCE_EXTRA_SCORE = 2000
POWERUP_CHANCE_SPAWN = 0.05

TRONCO_SLOTS_OPCOES = [2, 3]
BIOMAS = ["grama", "areia", "gelo"]
CICLO_BIOMA_DURACAO = 50

POWERUP_XP2_DURACAO_MS = 8000
MAX_POWERUPS_ATIVOS = 1

TIPO_GRAMA = "grama"
TIPO_ESTRADA = "estrada"
TIPO_RIO = "rio"

ESTADO_MENU = 0
ESTADO_JOGANDO = 1
ESTADO_GAMEOVER = 2
ESTADO_NEW_PLAYER = 3
ESTADO_LOAD_PLAYER = 4
ESTADO_OPTIONS = 5
ESTADO_CONTROLS = 6
ESTADO_LEADERBOARD = 7

SCORE_DIFICULDADE_MAX = 200 # Pontuação onde os obstáculos atingem velocidade/densidade máxima

# Breakpoints e Pesos de Geração (Grama, Estrada, Rio)
BREAKPOINT_FASE2 = 100
BREAKPOINT_FASE3 = 200
PESOS_GRID_FASE1 = [70, 20, 10] # Início: Muito mato, pouca rua, zero rios
PESOS_GRID_FASE2 = [45, 35, 20] # Meio: Balanceado
PESOS_GRID_FASE3 = [30, 45, 25] # Fim: Caos urbano e muita água

# Velocidades (Min, Max) base -> escalam até -> (Min, Max) no teto de dificuldade
CARRO_VEL_BASE = (3.5, 6.0)
CARRO_VEL_TETO = (7.0, 11.0)

TRONCO_VEL_BASE = (2.0, 3.5)
TRONCO_VEL_TETO = (3.5, 6.0)

# Espaçamento de Spawn em Pixels (Min, Max) base -> escalam até -> (Min, Max) no teto
CARRO_SPAWN_BASE = (250, 450)
CARRO_SPAWN_TETO = (120, 220)

TRONCO_SPAWN_BASE = (200, 400)
TRONCO_SPAWN_TETO = (100, 220)

BIOMA_POPUP_DURACAO = 1200